# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.1.0
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cache-wisely
  name: monitoring
spec:
  containers:
    - name: prometheus
      image: docker.io/prom/prometheus:latest
      restartPolicy: Always
      args:
        - '--log.level=debug'
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - containerPort: 9090
          hostPort: 9090
      volumeMounts:
        - mountPath: /prometheus
          name: prometheus-data
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config
    - name: grafana
      image: docker.io/grafana/grafana:latest
      restartPolicy: Always
#      env:
#        - name: GF_AUTH_ANONYMOUS_ENABLED
#          value: 'true'
#        - name: GF_AUTH_ORG_ROLE
#          value: Admin
#        - name: GF_AUTH_DISABLE_LOGIN_FORM
#          value: 'true'
      ports:
        - containerPort: 3000
          hostPort: 3000
      volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
        - mountPath: /etc/grafana/provisioning
          name: grafana-provisioning
  volumes:
    - name: prometheus-data
      persistentVolumeClaim:
        claimName: prometheus-data
    - name: prometheus-config
      hostPath:
        path: ${PWD}/prometheus.yml
        type: File
    - name: grafana-data
      persistentVolumeClaim:
        claimName: grafana-data
    - name: grafana-provisioning
      hostPath:
        path: ${PWD}/grafana
