apiVersion: 1
deleteDatasources:
datasources:
- id: 3
  name: Prometheus
  type: prometheus
  typeName: Prometheus
  typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
  access: proxy
  url: http://127.0.0.1:9090
  user: ''
  database: ''
  basicAuth: false
  isDefault: false
  jsonData:
    httpMethod: POST
  readOnly: false
